import { AgeRange, defaultAgeRange, Person, PersonId } from '../../../types.js';

const players: Record<PersonId, Person> = {
  'daenerys-targaryen': {
    id: 'daenerys-targaryen',
    firstname: 'Daenerys',
    lastname: 'Targaryen',
    gender: 'female',
    email: 'daenerys@targaryen.com',
    age: AgeRange['14-17'],
    exclude: ['jon-snow'],
    archived: false,
  },
  'viserys-targaryen': {
    id: 'viserys-targaryen',
    firstname: 'Viserys',
    lastname: 'Targaryen',
    gender: 'male',
    email: 'viserys@targaryen.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'robb-stark': {
    id: 'robb-stark',
    firstname: 'Robb',
    lastname: 'Stark',
    gender: 'male',
    email: 'robb@stark.com',
    age: AgeRange['14-17'],
    exclude: [],
    archived: false,
  },
  'bran-stark': {
    id: 'bran-stark',
    firstname: 'Bran',
    lastname: 'Stark',
    gender: 'male',
    email: 'bran@stark.com',
    age: AgeRange['10-13'],
    exclude: [],
    archived: false,
  },
  'roose-bolton': {
    id: 'roose-bolton',
    firstname: 'Roose',
    lastname: 'Bolton',
    gender: 'male',
    email: 'roose@bolton.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'ned-stark': {
    id: 'ned-stark',
    firstname: 'Ned',
    lastname: 'Stark',
    gender: 'male',
    email: 'ned@stark.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'jon-snow': {
    id: 'jon-snow',
    firstname: 'Jon',
    lastname: 'Snow',
    gender: 'male',
    email: 'jon@snow.com',
    age: AgeRange['14-17'],
    exclude: ['daenerys-targaryen'],
    archived: false,
  },
  'tyrion-lannister': {
    id: 'tyrion-lannister',
    firstname: 'Tyrion',
    lastname: 'Lannister',
    gender: 'male',
    email: 'tyrion@lannister.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'cersei-lannister': {
    id: 'cersei-lannister',
    firstname: 'Cersei',
    lastname: 'Lannister',
    gender: 'female',
    email: 'cersei@lannister.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'arya-stark': {
    id: 'arya-stark',
    firstname: 'Arya',
    lastname: 'Stark',
    gender: 'female',
    email: 'arya@stark.com',
    age: AgeRange['10-13'],
    exclude: [],
    archived: false,
  },
  'sansa-stark': {
    id: 'sansa-stark',
    firstname: 'Sansa',
    lastname: 'Stark',
    gender: 'female',
    email: 'sansa@stark.com',
    age: AgeRange['14-17'],
    exclude: ['petyr-baelish'],
    archived: false,
  },
  'jaime-lannister': {
    id: 'jaime-lannister',
    firstname: 'Jaime',
    lastname: 'Lannister',
    gender: 'male',
    email: 'jaime@lannister.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'joffrey-baratheon': {
    id: 'joffrey-baratheon',
    firstname: 'Joffrey',
    lastname: 'Baratheon',
    gender: 'male',
    email: 'joffrey@baratheon.com',
    age: AgeRange['14-17'],
    exclude: [],
    archived: false,
  },
  'theon-greyjoy': {
    id: 'theon-greyjoy',
    firstname: 'Theon',
    lastname: 'Greyjoy',
    gender: 'male',
    email: 'theon@greyjoy.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'tywin-lannister': {
    id: 'tywin-lannister',
    firstname: 'Tywin',
    lastname: 'Lannister',
    gender: 'male',
    email: 'tywin@lannister.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
  'petyr-baelish': {
    id: 'petyr-baelish',
    firstname: 'Petyr',
    lastname: 'Baelish',
    gender: 'male',
    email: 'petyr@baelish.com',
    age: defaultAgeRange,
    exclude: [],
    archived: false,
  },
};

export default players;
